server:
  port: 10020

spring:
  application:
    name: kafka-stream10020


  cloud:
    stream:
      ## 一定得加这个，不然多个consumer无法消费到消息
      function:
        definition: person;student;student2;student3
      kafka:
        binder:
          auto-create-topics: true   # 自动创建topics
          brokers: localhost:9097,localhost:9098,localhost:9099
      bindings:
        student-out-0:
          destination: student
          content-type: application/json
        student-in-0:
          destination: student
          group: student_group
        student2-in-0:
          destination: student
          group: student_group
        student3-in-0:
          destination: student
          group: student3_group

#        student2-out-0:
#          destination: student
#          content-type: application/json
#        student2-in-0:
#          destination: student
#          group: student_group
#
#        student3-out-0:
#          destination: student
#          content-type: application/json
#        student3-in-0:
#          destination: student
#          group: student3_group




        person-out-0:
          destination: person
          content-type: application/json
        person-in-0:
          destination: person
          group: person_group





